# Site settings
title: Ethan O'Hanlon
email: ethan.ohanlon@yahoo.com
url: https://github.com/EOHanlon243
description: "Hello, I'm Ethan! I'm a Game Developer and recent graduate from the University of Portsmouth."
keywords: "portfolio, game, gaming, programmer, development"
skills: "Games Programmer"
meta_author: O'Hanlon Ethan

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2f2f2f # About / Buttons 
  primary-rgb: "0, 92, 41" # Star/ Modal Hover 
  secondary: 2f2f2f #Nav Bar / Down Button / Title Text / Social Links 
  secondary-dark: 005c29 #Section Highlight / Copyright 005c29

# Footer settings
footer:
  copyright: Ethan O'Hanlon
  CV: CV
  social: Social Links
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ethanohanlon/
  - title: github
    url: https://github.com/EOHanlon243
  - title: itch
    url: https://eohanlon243.itch.io/

# Postal address (add as many lines as necessary)
address:
  - line: CV on request

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
